config/routes.rb
Rails.application.routes.draw do


  # get 'products/index'
  # get 'products/show'
  # get 'products/new'
  # get 'products/create'
  # get 'products/edit'
  # get 'products/update'

  devise_for :users
	root 'application#select_home_page'
  resources :products
	resources :posts do
		resources :comments
    resources :loves
	end

post 'import' => 'products#import'

get 'export' => 'products#export'
# get '/posts/:id', to: 'posts#mypost', as: 'mypostt'

get 'mypost' => 'posts#mypost'
# get 'like' => 'posts#like'
get 'userdetail' => 'posts#userdetail'
get 'demo' => 'posts#demo'
	 


  # get 'posts/indmypost
  # get 'posts/show'
  # get 'posts/edit'
  # get 'posts/create'
  # get 'posts/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :post

	belongs_to :user

	has_attached_file :image, styles:{large: "150x150", medium: "100x100", thumb: "50x50"}

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	scope :sorted, lambda { order("sections.position ASC") }
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

	# def create
 #        @post = Post.find(params[:post_id])
 #         @comment = @post.comments.create(params[:comment].permit(:comment))
 #         comment.
 #        redirect_to post_path(@post)
 #    end

    def edit
        # render json: params and return

        @comment = Comment.find(params[:id])
        @post = Post.find(params[:post_id])
        respond_to do |format|
            format.js {}
            format.html {}

        end
        # @posts = @post.current_user.posts
        # @section_count = Section.count
    end

    def update
        @comment = Comment.find(params[:id])
        @post = Post.find(params[:post_id])

        # @comment.image_file_name = @post.image_file_name
        # @comment.image_content_type = @post.image_content_type
        # @comment.image_file_size = @post.image_file_size

        if @comment.update(comment_params)
            respond_to do|format|
                format.js
                format.html { redirect_to @comment.post }
            end
        else
            @posts = @post.current_user.posts
            respond_to do|format|
                format.js
                format.html { render('edit') }
            end
        end

        # @comment = Comment.find(params[:id])
        
        # if @comment.update(comment_params)
        #     redirect_to @post
        # else
        #     render 'edit'
        # end
    end

    #def new
     #   @comment = Comment.new
    #end

    def create
        @post = Post.find(params[:post_id])

        @comment = current_user.comments.new(comment_params)

        @comment.post_id = @post.id
        @comment.user_id = current_user.id
        @comment.image_file_name = @post.image_file_name
        @comment.image_content_type = @post.image_content_type
        @comment.image_file_size = @post.image_file_size

        # params.to_json and return

        @comment.save
        respond_to do |format|
            format.js
            format.html { redirect_to post_path(@comment.post) }
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.js
            format.html { redirect_to post_path(@post) }
        end
        
    end

    private

    def comment_params
        params.require(:comment).permit(:comment)
    end


    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="box" >
  <article class="media">
    <div class="media-content" id="comnew">
      <div class="content" id="comment-<%=comment.id%>">
        <p class="com">
          <%= image_tag @post.image.url(:thumb) %>
          <strong>
            <%= comment.user.email %>
          </strong>
          <strong>
            <%= ': :'  %>
          </strong>
          <%= comment.comment %>
        </p>
        <br/>
      </div>
    </div>
    <div>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% if current_user.id == comment.user_id %>
      <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' },remote: true %>
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'Edit ', edit_post_comment_path(@post, comment),remote: true, class: 'btn btn-xs btn-primary' %>
      <% end %>
   </div>

  </article>
</div>

app/views/comments/_editform.html.erb
<%= simple_form_for [post, comment], remote: true do |f| %>
    <div>
      <%= f.text_field :comment, class: 'form-control commentbox', autofocus: true, :id => 'commentbox' %>
    </div>

    <div style="padding-top:20px;">
       <%= f.submit "update comment",class: 'btn btn-primary' %>

    </div>
    <% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @comment || @post.comments.build], remote: true) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }  %>
  </div>
</div>
<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
<% end %>



  

app/views/comments/create.js.erb
$('#comments-list').append('<%= escape_javascript(render partial: "comments/comment", locals:{comment: @comment, post: @post}) %>');
$('#comment-form').html('<%= escape_javascript(render :partial => "comments/form", locals:{post: @post}) %>');
$('.textarea').val('');

app/views/comments/destroy.js.erb
$('#comments-list').html('<%= escape_javascript(render partial: @post.comments) %>');

app/views/comments/edit.html.erb
<div id= "comment-form">
<% content_for :page_title, "Edit Comment" %>
<%= render :partial => 'comments/editform', locals:{post: @post, comment: @comment}%>
</div>

app/views/comments/edit.js.erb
$('#comment-<%=@comment.id%>').html('<%= escape_javascript(render :partial => "comments/editform", locals:{post: @post, comment: @comment}) %>');

app/views/comments/update.js.erb
$('#comment-<%=@comment.id%>').html("<%= escape_javascript(render :partial => 'comments/comment', locals:{post: @post, comment: @comment}) %>");