config/routes.rb
Rails.application.routes.draw do


  # get 'products/index'
  # get 'products/show'
  # get 'products/new'
  # get 'products/create'
  # get 'products/edit'
  # get 'products/update'

  devise_for :users
	root 'application#select_home_page'
  resources :products
	resources :posts do
		resources :comments
    resources :loves
	end

post 'import' => 'products#import'

get 'export' => 'products#export'
# get '/posts/:id', to: 'posts#mypost', as: 'mypostt'

get 'mypost' => 'posts#mypost'
# get 'like' => 'posts#like'
get 'userdetail' => 'posts#userdetail'
get 'demo' => 'posts#demo'
	 


  # get 'posts/indmypost
  # get 'posts/show'
  # get 'posts/edit'
  # get 'posts/create'
  # get 'posts/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :loves

	has_many :comments, dependent: :destroy

	belongs_to :user

	has_attached_file :image, styles:{large: "150x150", medium: "100x100", thumb: "50x50"}

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!, except: [:index]

    def demo
    end

    def userdetail
        @user = User.find(current_user.id)
    end

    # def like 
    #     if session[:vvlike].nil?
    #         session[:vvlike]=1
    #     else
    #         session[:vvlike] +=1
    #     end
    #     redirect_to posts_path
    # end

    def index
        # flash[:signin] = "You need to sign in first"
        # session[:vlike] ||= 0
        # session[:vlike] += 1
        @posts = Post.all.order("created_at DESC")
    end

    def mypost
        @posts = current_user.posts
    end


    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.new(post_params)
        # @post.user_id = current_user

        # params.to_json and return

        if @post.save!
            redirect_to mypost_path
        else
            render 'new'
        end
    end

    def show
        @userlove = Love.where("user_id = ? AND post_id = ?", current_user.id, params[:id])
        @post = Post.find(params[:id])
        @comments = @post.comments.order('created_at desc')
        @love = Love.where("post_id = ?", params[:id])
        @countlove = @love.size
        # @post = Post.find(current_user)
        # @post = Post.find(params[:id])
    end

    def update
        # @post = Post.find(current_user)
        @post = Post.find(params[:id])
        
        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end

    def edit
        @post = mypost.find(params[:id])
        # @post = Post.find(params[:id])
    end

    def destroy
        # @post = Post.find(current_user)
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to mypost_path

    end

    private

    def post_params
        params.require(:post).permit(:image, :title, :content)
    end

  def delete
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post, html: { multipart: true } do |f| %>

  <div class="field">
    <div class="control">
      <%= f.input :image, input_html: { class: 'input' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' } %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/_like.html.erb
<% if @love.empty? %>
	<%= link_to "love", post_loves_path(@post), method: :post, remote: true %>     
    <% else %>
    <%= link_to "unlove", post_lofe_path(@post), method: :delete, remote: true %>
<% end %>     
<%= @countlove %>&nbsp;&nbsp;<%= "loves" %>

app/views/posts/demo.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md">
      <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-secondary">Left</button>
        <button type="button" class="btn btn-secondary">Middle</button>
        <button type="button" class="btn btn-secondary">Right</button>
      </div>
    </div>
    <div class="col-md">
      <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-secondary">Left</button>
        <button type="button" class="btn btn-secondary">Middle</button>
        <button type="button" class="btn btn-secondary">Right</button>
      </div>
    </div>
    <div class="col-md">
      <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-secondary">Left</button>
        <button type="button" class="btn btn-secondary">Middle</button>
        <button type="button" class="btn btn-secondary">Right</button>
      </div>
    </div>
  </div>
  
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>
<div class="section">
    <div class="container">
        <% @posts.each do |post| %>
            <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <%= image_tag post.image.url(:thumb) %> 
                <p class="title is-4"><%= link_to post.title, post  %></p>
              </div>
            </div>
            <div class="content">
                 <%= post.content %>
            </div>
            <div class="comment-count">
                <span class="tag is-rounded"><%= post.comments.count %> comments</span>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                               
            </div>
          </div>
        </div>
        <% end %>
    </div>
</div>

app/views/posts/mypost.html.erb
<section class="section">
    <div class="container">
        <nav class="level">
        	<div class="content">
        		<% @posts.each do |i| %>
        		<p><strong><%="Title is:" %><%= i.title %></strong><br/>
        		<p><%= "Post is :" %><%= i.content %><br/>
        			<div class="level-right">
                		<%= link_to "Edit", edit_post_path(i), class:"button" %>
              			                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;

                		<%= link_to "Delete", post_path(i), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
                		
          			</div>
        		</p>
        		</p>
            	<%end%>
        </div>
    </nav>
    </div>
    </section>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
    <div class="container">
        <nav class="level">
          <!-- Left side -->
          <div class="level-left">
            <p class="level-item">
                <strong></strong>
            </p>
          </div>
          <!-- Right side -->
        </nav>
        <hr/>

        <div class="content">
            <strong>
            <%= image_tag @post.image.url(:thumb) %>

            <h2><%= @post.content %></h2>
        </strong>
        <div id="likeunlike">
            <% if @userlove.size==0 %>
            <%= link_to "love", post_loves_path(@post), method: :post, remote: true %>
                &nbsp;&nbsp;&nbsp;&nbsp;
            <% else %>
            <%= link_to "unlove", post_lofe_path(@post), method: :delete, remote: true %>
            <% end %>
            
            <%= @countlove %>&nbsp;&nbsp;<%= "loves" %>
        </div>
        </div>
    </div>
    </section>
    <br/><br/>
<section class="section comments">
    <div class="container">
        <h3 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h3>
        &nbsp;&nbsp;&nbsp;&nbsp;
        
        

        <div id="comments-list" class="comments-list">
            <% @post.comments.each do |comment| %>
            
            <%= render partial: "comments/comment", locals:{post: @post, comment: comment} %>
            <% end %>
        </div>
        
        <div class="comment-form", id="comment-form">
            <hr />
            <h4 class="subtitle is-3">Leave a comment</h4>
                 <%= render :partial => 'comments/form', locals:{post: @post}%>
        </div>
    </div>
</section>

app/views/posts/userdetail.html.erb
<%= @user.email %>