config/routes.rb
Rails.application.routes.draw do


  # get 'products/index'
  # get 'products/show'
  # get 'products/new'
  # get 'products/create'
  # get 'products/edit'
  # get 'products/update'

  devise_for :users
	root 'application#select_home_page'
  resources :products
	resources :posts do
		resources :comments
    resources :loves
	end

post 'import' => 'products#import'

get 'export' => 'products#export'
# get '/posts/:id', to: 'posts#mypost', as: 'mypostt'

get 'mypost' => 'posts#mypost'
# get 'like' => 'posts#like'
get 'userdetail' => 'posts#userdetail'
get 'demo' => 'posts#demo'
	 


  # get 'posts/indmypost
  # get 'posts/show'
  # get 'posts/edit'
  # get 'posts/create'
  # get 'posts/delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

  <div class="p-3 mb-2 bg-dark text-white">
      <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'All Posts', posts_path, class: "navbar-item" %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to 'show my posts', mypost_path, class: "navbar-item" %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= link_to 'User Detail', userdetail_path, class: "navbar-item" %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to "Create New Post", new_post_path(), class: "navbar-item" %>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to "Import File", products_path(), class: "navbar-item" %>

                <% if user_signed_in?%>
                  <div class="nav justify-content-end">
                    <%= link_to "logout" , destroy_user_session_path, method: :delete , data: { confirm: "Are you sure?" }, class:"button is-danger" %>
                </div>
                <% else %>
                  <%= link_to "SignUp", new_user_registration_path(), class: "navbar-item" %>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                
                <%= link_to "Login", new_user_session_path(), class: "navbar-item" %>
                <%end%>
                  
              
              </div>
            </div>
            
        </nav>
      </div>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <% flash.each do |name, msg| %>
            <div class='alert alert-<%= name%>' role="alert">
              <%= msg%>
            </div>
            <%end%>
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>
  </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<title>Login Page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Sign up page', homes_path, class: "navbar-item" %>
              <span class="navbar-burger burger" data-target="navbarMenuHeroA">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to "Login Page", home_path, class:"navbar-item" %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield :page_title %>
          </h1>
        </div>
      </div>
    </section>
    <%= yield %>
  </body>
</html>